### ISSUE TITLE
Kanban board setup

### ISSUE THREAD

**Issue by sajibarafatsiddiqui** [sajibarafatsiddiqui/final-capstone-project#1]
We are three members in our team. @Solobarine, @chiztechnology and me myself @sajibarafatsiddiqui .

Our link for project:
https://github.com/sajibarafatsiddiqui/final-capstone-project/projects/1 
<img width="902" alt="image" src="https://github.com/sajibarafatsiddiqui/final-capstone-project/assets/39811497/4668c44f-daef-4c4a-b99d-6b07a53f6dbc">

In this project, we are going to create a website for car renting services. Here one will be able to create requests for renting cars. There will be options with a list of cars for renting. 

Thanks.

**Comment by Meltrust** [comment]
Hi team

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks have been assigned✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [x] According to the project requirements:

![image](https://github.com/sajibarafatsiddiqui/final-capstone-project/assets/57421823/ace6ad87-43ab-47ef-9fae-4226bb72faf4)

This one does not have any pointings:

![image](https://github.com/sajibarafatsiddiqui/final-capstone-project/assets/57421823/2a3617c9-25a7-4947-88b5-ff3eb0825233)

Kindly, add some points to it.  Remember to keep the pointings equal and fair, according to the same requirement.

That way, we will meet all the requirements. 💪 

- [x] I couldn't find this task on your Kanban board:

![image](https://github.com/sajibarafatsiddiqui/final-capstone-project/assets/57421823/75d20e3c-3515-40ab-980f-b77c35fbea6c)

Kindly add this task if it does not exist yet.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
_note: I tried to contact the student to offer help.  Got no response._

Hi @sajibarafatsiddiqui,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

 ## Required Changes ♻️

- [ ] Good job adding the task for API documentation.  However, the card does not have any description.

![image](https://github.com/sajibarafatsiddiqui/final-capstone-project/assets/57421823/905c91cd-5f5b-42cb-87a3-b163841d6642)

Kindly, add a description for this new card so it meets the requirements, as the others.


- [ ]  This task still does not have any pointings:

![image](https://github.com/sajibarafatsiddiqui/final-capstone-project/assets/57421823/11038148-8330-42ed-812a-d469df565e4e)

You can just edit the name of the task and add the points.

After this, please ensure the pointings are still equal, and fair.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sajibarafatsiddiqui** [comment]
<img width="921" alt="image" src="https://github.com/sajibarafatsiddiqui/final-capstone-project/assets/39811497/48e58aba-96f7-4687-ac5f-0c10e8ddbe45">

Added pt to the issue mentioned.
Added the issue missed.

Thanks

**Comment by Meltrust** [comment]
Hi @sajibarafatsiddiqui,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All the requirements and requested changes were made carried out.  Good job/.✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
